GENERAL_CONFIG = 'GENERAL_CONFIG'

OUTPUT_PATH = 'OUTPUT_PATH'
PIXEL_RANGE = 'PIXEL_RANGE'
IMAGE_SHAPE = 'IMAGE_SHAPE'


TARGET_CLASSIFIER_PATH = 'TARGET_CLASSIFIER_PATH'

IMAGES_FILE_PATH = 'IMAGES_FILE_PATH'
LABELS_FILE_PATH = 'LABELS_FILE_PATH'
LIMIT_PER_LABEL = 'LIMIT_PER_LABEL'

FGSM = 'FGSM'
MI_FGSM = 'MI-FGSM'
BIM = 'BIM'
CW_L2 = 'CW L2'
GAUSS = 'GAUSS'

EPSILON = 'EPSILON'
BATCH_SIZE = 'BATCH_SIZE'
ENABLE = 'ENABLE'
N_ITERATIONS = 'N_ITERATIONS'
MAX_BALL = 'MAX_BALL'
CONFIG_FILEPATH = 'CONFIG_FILEPATH'
DECAY_FACTOR = 'DECAY_FACTOR'
CONFIDENCE = 'CONFIDENCE'
TRUE = 'True'
FALSE = 'False'
TARGETED = 'TARGETED'

DEFAULT_OUTPUT_PATH = './output'
