GENERAL_CONFIG = 'GENERAL_CONFIG'

OUTPUT_PATH = 'OUTPUT_PATH'
PIXEL_RANGE = 'PIXEL_RANGE'

TARGET_CLASSIFIER_PATH = 'TARGET_CLASSIFIER_PATH'

IMAGES_FILE_PATH = 'IMAGES_FILE_PATH'
LABELS_FILE_PATH = 'LABELS_FILE_PATH'

DEFAULT_OUTPUT_PATH = './ad4ad_output'

ADVERSARIAL_FOLDER = 'ADVERSARIAL_FOLDER'
GT_ORIGINAL_FOLDER = 'GT_ORIGINAL_FOLDER'
GT_LABELS_FOLDER = 'GT_LABELS_FOLDER'

ORIGINAL_IMAGES_FILE = 'ORIGINAL_IMAGES_FILE'
ORIGINAL_LABELS_FILE = 'ORIGINAL_LABELS_FILE'

TRAINING_CONFIG = 'TRAINING_CONFIG'
AUTOENCODER_PATH = 'AUTOENCODER_PATH'
DEFAULT_AUTOENCODER_PATH = './results'
EPOCHS = 'EPOCHS'
VALID_RATIO = 'VALID_RATIO'
BATCH_SIZE = 'BATCH_SIZE'
LEARNING_RATE = 'LEARNING_RATE'
EARLY_STOPPING = 'EARLY_STOPPING'
MIN_DELTA = 'MIN_DELTA'

LOSS = 'LOSS'

MSE_CE = 'MSE_CE'
MSE = 'MSE'
MSE_CE_O = 'MSE_CE_0'

TRUE = 'True'


