GENERAL_CONFIG = 'GENERAL_CONFIG'

OUTPUT_PATH = 'OUTPUT_PATH'
PIXEL_RANGE = 'PIXEL_RANGE'

TARGET_CLASSIFIER_PATH = 'TARGET_CLASSIFIER_PATH'

DEFAULT_OUTPUT_PATH = './ad4ad_output'

DATA_CONFIG = 'DATA_CONFIG'

ADVERSARIAL_FOLDER = 'ADVERSARIAL_FOLDER'
GT_ORIGINAL_FOLDER = 'GT_ORIGINAL_FOLDER'
GT_LABELS_FOLDER = 'GT_LABELS_FOLDER'

ORIGINAL_IMAGES_FILE = 'ORIGINAL_IMAGES_FILE'
ORIGINAL_LABELS_FILE = 'ORIGINAL_LABELS_FILE'

TRAINING_CONFIG = 'TRAINING_CONFIG'
AUTOENCODER_PATH = 'AUTOENCODER_PATH'
DEFAULT_AUTOENCODER_PATH = './results'
EPOCHS = 'EPOCHS'
VALID_RATIO = 'VALID_RATIO'
BATCH_SIZE = 'BATCH_SIZE'
LEARNING_RATE = 'LEARNING_RATE'
EARLY_STOPPING = 'EARLY_STOPPING'
MIN_DELTA = 'MIN_DELTA'

LOSS = 'LOSS'

MSE_CE = 'mse_ce'
MSE = 'mse'
MSE_CE_O = 'mse_ce_0'

TRUE = 'True'


